### ISSUE TITLE
Pdf pcb+sch

### ISSUE THREAD

**Issue by Testato** [valerionew/colors-of-italy#32]
Per chi al volo, magari su smartphone, vuole dare un'occhiata a schema elettrico e pcb, è utile inserire due .pdf aggiornati di volta in volta all'ultima release

**Comment by valerionew** [comment]
Grazie per il suggerimento, fatto in 288a203!

**Comment by Testato** [comment]
è stato aggiunto solo il .pdf dello schema, non anche il .pdf del pcb ?

**Comment by Testato** [comment]
Closed by https://github.com/valerionew/colors-of-italy/commit/67d5a37c0be215f8fd7a4a17aa0f6b96717bcda0
