### ISSUE TITLE
fetch dei dati

### ISSUE THREAD

**Issue by WAPEETY** [valerionew/colors-of-italy#33]
Salve, per essere sicuri che i dati siano sempre aggiornati non converrebbe prenderli da [https://github.com/pcm-dpc/COVID-19](https://github.com/pcm-dpc/COVID-19) ?

vi ringrazio in anticipo per la risposta.

**Comment by valerionew** [comment]
Ciao e grazie per il suggerimento.
Quelli distribuiti dalla protezione civile sono dei [JSON enormi](https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/aree/geojson/dpc-covid-19-ita-aree.json), non è molto conveniente scaricarli e parsarli sul dispositivo. In più avevamo già questi dati per un altro progetto di @lorossi, che fa scraping su una pagina del ministero, quindi sono comunque aggiornati

**Comment by WAPEETY** [comment]
In effetti ho notato adesso, scaricarli e parsarli su un ESP sarebbe praticamente una mazzata mazzata per il microcontrollore ahahahah. 
Grazie ancora, chiudo la issue
